-- The certificate challenge: every proof of the record, stated over its concept
-- packages alone. Generated by lax; `lake comparator` holds the Solution to it.
import Lax38

theorem Cert.Lax38Proofs.hasSucc : _root_.Lax38.Order.HasSucc := sorry
