-- The certificate solution: the Challenge's theorems, each discharged by the
-- record's own proof. Generated by lax.
import Lax38Proofs

theorem Cert.Lax38Proofs.hasSucc : _root_.Lax38.Order.HasSucc := @_root_.Lax38Proofs.hasSucc
