import Lax68.Planar
import Lax68.Outerplanar
import Lax68.MaximalOuterplanar
import Lax68.GridsAndWalls
import Lax68.Triangles
import Lax68.Stars
import Lax68.Ladders
import Lax68.HalinGraphs
import Lax68.Wheels
import Lax68.SeriesParallel
import Lax68.Trees
import Lax68.Paths
import Lax68.Triangulations
import Lax68.Relationships
