-- The certificate challenge: every proof of the record, stated over its concept
-- packages alone. Generated by lax; `lake comparator` holds the proof package to it.
import Lax261
import Lax42

theorem Lax261Proofs.aux : _root_.Lax261.Infinite.Auxiliary := sorry

theorem Lax261Proofs.euclid
    (h₁ : _root_.Lax42.Primes.ExistsPrimeDivisor)
    (h₂ : _root_.Lax261.Infinite.Auxiliary)
    (h₃ : _root_.Lax42.Primes.ExistsPrimeDivisor)
    (h₄ : _root_.Lax261.Infinite.Auxiliary)
    : _root_.Lax261.Infinite.InfinitelyManyPrimes := sorry
