-- The certificate challenge: every proof of the record, stated over its concept
-- packages alone. Generated by lax; `lake comparator` holds the proof package to it.
import Spec2

theorem Spec2.Basic.polyProof.{«w»}
    (h₁ : _root_.Spec2.Basic.Poly.{«w»})
    : _root_.Spec2.Basic.Poly.{«w»} := sorry
