-- The certificate challenge: every proof of the record, stated over its concept
-- packages alone. Generated by lax; `lake comparator` holds the Solution to it.
import Spec2

theorem Cert.Spec2.Basic.«证明».{«λ»}
    (h₁ : _root_.Spec2.Basic.Closed)
    : _root_.Spec2.Basic.«定理».{«λ»} := sorry
