-- The certificate solution: the Challenge's theorems, each discharged by the
-- record's own proof. Generated by lax.
import Spec2

theorem Cert.Spec2.Basic.polyProof.{w}
    (h₁ : _root_.Spec2.Basic.Poly.{w})
    : _root_.Spec2.Basic.Poly.{w} := @_root_.Spec2.Basic.polyProof.{w} h₁
