-- The certificate solution: the Challenge's theorems, each discharged by the
-- record's own proof. Generated by lax.
import Spec2

theorem Cert.Spec2.Basic.«证明».{«λ»}
    (h₁ : _root_.Spec2.Basic.Closed)
    : _root_.Spec2.Basic.«定理».{«λ»} := @_root_.Spec2.Basic.«证明».{«λ»} h₁
