-- The certificate challenge: every proof of the record, stated over its concept
-- packages alone. Generated by lax; `lake comparator` holds the Solution to it.
import Lax38

theorem Cert.Lax38Proofs.refl_of_hasSucc.{«u», «v»}
    (h₁ : _root_.Lax38.Order.HasSucc)
    (h₂ : _root_.Lax38.Order.Refl.{«v»})
    : _root_.Lax38.Order.Both.{«u», «v»} := sorry
