-- The certificate solution: the Challenge's theorems, each discharged by the
-- record's own proof. Generated by lax.
import Lax38Proofs

theorem Cert.Lax38Proofs.refl_of_hasSucc.{«u», «v»}
    (h₁ : _root_.Lax38.Order.HasSucc)
    (h₂ : _root_.Lax38.Order.Refl.{«v»})
    : _root_.Lax38.Order.Both.{«u», «v»} := @_root_.Lax38Proofs.refl_of_hasSucc.{«u», «v»} h₁ h₂
