-- The certificate challenge: every proof of the record, stated over its concept
-- packages alone. Generated by lax; `lake comparator` holds the proof package to it.
import Lax7

theorem Lax7Proofs.«theorem».good?.{«fun»}
    (h₁ : _root_.Lax7.Facts.℘)
    : _root_.Lax7.Facts.α'.{«fun»} := sorry
