-- The certificate challenge: every proof of the record, stated over its concept
-- packages alone. Generated by lax; `lake comparator` holds the Solution to it.
import Lax7

theorem Cert.Lax7Proofs.«theorem».«定理».{«λ»}
    (h₁ : _root_.Lax7.Facts.«fun»)
    : _root_.Lax7.Facts.α'.{«λ»} := sorry
