-- The certificate solution: the Challenge's theorems, each discharged by the
-- record's own proof. Generated by lax.
import Lax7Proofs

theorem Cert.Lax7Proofs.«theorem».«定理».{«λ»}
    (h₁ : _root_.Lax7.Facts.«fun»)
    : _root_.Lax7.Facts.α'.{«λ»} := @_root_.Lax7Proofs.«theorem».«定理».{«λ»} h₁
