-- The certificate solution: the Challenge's theorems, each discharged by the
-- record's own proof. Generated by lax.
import Lax7Proofs

theorem Cert.Lax7Proofs.«theorem».good?.{«fun»}
    (h₁ : _root_.Lax7.Facts.℘)
    : _root_.Lax7.Facts.α'.{«fun»} := @_root_.Lax7Proofs.«theorem».good?.{«fun»} h₁
