// The relative-certificate composer (certify/compose.ts) over a fixture chain:
// the Solution body is held to a golden text, the universe substitution is
// exercised through a polymorphic conclusion, and every refusal names its
// rule. The witness forest is given by hand here; `lax certify` takes it from
// selectProofTree (test/unit/cli-certify.test.ts covers that glue).

import { describe, expect, it } from "vitest";
import { CompositionError, composeRelativeCertificate } from "../../src/submission-validation/certify/compose.js";
import { relativeCertificateFiles, type CertifiedProof } from "../../src/submission-validation/certify/generate.js";

const proof = (
  id: string,
  levelParams: string[],
  hypotheses: Array<[string, string[]]>,
  conclusion: [string, string[]],
): CertifiedProof => ({
  id,
  levelParams,
  telescope: {
    hypotheses: hypotheses.map(([statement, levels]) => ({ statement, levels })),
    conclusion: { statement: conclusion[0], levels: conclusion[1] },
  },
});

/** lax-42 states and proves `ExistsPrimeDivisor` (outright, in lax-7's proof
 * package) and `InfinitelyManyPrimes.{u}` from it; lax-261 states
 * `Corollary.{a, b}` and proves it from `InfinitelyManyPrimes.{b}` and
 * `ExistsPrimeDivisor`, used twice. */
const PROOFS = new Map(
  [
    proof("Lax7Proofs.existsPrimeDivisor", [], [], ["Lax42.Primes.ExistsPrimeDivisor", []]),
    proof("Lax42Proofs.euclid", ["u"], [["Lax42.Primes.ExistsPrimeDivisor", []]], ["Lax42.Primes.InfinitelyManyPrimes", ["u"]]),
    proof(
      "Lax261Proofs.corollary",
      ["v", "w"],
      [
        ["Lax42.Primes.InfinitelyManyPrimes", ["w"]],
        ["Lax42.Primes.ExistsPrimeDivisor", []],
        ["Lax42.Primes.ExistsPrimeDivisor", []],
      ],
      ["Lax261.Infinite.Corollary", ["v", "w"]],
    ),
  ].map((entry) => [entry.id, entry]),
);

const WITNESS = new Map([
  ["Lax42.Primes.ExistsPrimeDivisor", "Lax7Proofs.existsPrimeDivisor"],
  ["Lax42.Primes.InfinitelyManyPrimes", "Lax42Proofs.euclid"],
  ["Lax261.Infinite.Corollary", "Lax261Proofs.corollary"],
]);

describe("composing a relative certificate", () => {
  it("applies the witnesses innermost first, substituting the demanded universe instance", () => {
    const composed = composeRelativeCertificate({
      target: { id: "Lax261.Infinite.Corollary", levelParams: ["a", "b"] },
      given: [],
      proofs: PROOFS,
      witness: WITNESS,
    });
    expect(composed.theorem).toEqual({
      name: "Cert.Lax261.Infinite.Corollary",
      levelParams: ["a", "b"],
      telescope: { hypotheses: [], conclusion: { statement: "Lax261.Infinite.Corollary", levels: ["a", "b"] } },
    });
    expect(composed.proofsUsed).toEqual(["Lax261Proofs.corollary", "Lax42Proofs.euclid", "Lax7Proofs.existsPrimeDivisor"]);
    expect(composed.conceptPackages).toEqual(["Lax261"]);
    expect(composed.proofPackages).toEqual(["Lax261Proofs", "Lax42Proofs", "Lax7Proofs"]);
    const files = relativeCertificateFiles({
      theorem: composed.theorem,
      body: composed.body,
      conceptPackages: composed.conceptPackages,
      proofPackages: composed.proofPackages,
    });
    expect(files["Solution.lean"]).toBe(
      "-- The certificate solution: the Challenge's theorem, discharged by the archive's proofs\n" +
        "-- applied along the proof network's witness forest. Generated by lax.\n" +
        "import Lax261Proofs\n" +
        "import Lax42Proofs\n" +
        "import Lax7Proofs\n" +
        "\n" +
        "theorem Cert.Lax261.Infinite.Corollary.{a, b} : _root_.Lax261.Infinite.Corollary.{a, b} :=\n" +
        "  @_root_.Lax261Proofs.corollary.{a, b}\n" +
        "    (@_root_.Lax42Proofs.euclid.{b} (@_root_.Lax7Proofs.existsPrimeDivisor))\n" +
        "    (@_root_.Lax7Proofs.existsPrimeDivisor)\n" +
        "    (@_root_.Lax7Proofs.existsPrimeDivisor)\n",
    );
    expect(files["Challenge.lean"]).toBe(
      "-- The certificate challenge: one statement proven relative to the given ones, stated over\n" +
        "-- the concept packages alone. Generated by lax; `lake comparator` holds the Solution to it.\n" +
        "import Lax261\n" +
        "\n" +
        "theorem Cert.Lax261.Infinite.Corollary.{a, b} : _root_.Lax261.Infinite.Corollary.{a, b} := sorry\n",
    );
    expect(JSON.parse(files["comparator.json"])).toMatchObject({ theorem_names: ["Cert.Lax261.Infinite.Corollary"] });
  });

  it("turns a given statement into the hypothesis the composition demands, in --relative-to order", () => {
    const composed = composeRelativeCertificate({
      target: { id: "Lax261.Infinite.Corollary", levelParams: ["a", "b"] },
      given: [
        { id: "Lax42.Primes.InfinitelyManyPrimes", levelParams: ["u"] },
        { id: "Lax42.Primes.ExistsPrimeDivisor", levelParams: [] },
      ],
      proofs: PROOFS,
      witness: WITNESS,
    });
    // the polymorphic given is demanded at `b`, the Cert theorem's own parameter
    expect(composed.theorem.telescope.hypotheses).toEqual([
      { statement: "Lax42.Primes.InfinitelyManyPrimes", levels: ["b"] },
      { statement: "Lax42.Primes.ExistsPrimeDivisor", levels: [] },
    ]);
    expect(composed.body).toBe("@_root_.Lax261Proofs.corollary.{a, b} h₁ h₂ h₂");
    expect(composed.proofsUsed).toEqual(["Lax261Proofs.corollary"]);
    expect(composed.conceptPackages).toEqual(["Lax261", "Lax42"]);
    const files = relativeCertificateFiles({
      theorem: composed.theorem,
      body: composed.body,
      conceptPackages: composed.conceptPackages,
      proofPackages: composed.proofPackages,
    });
    expect(files["Challenge.lean"]).toContain(
      "theorem Cert.Lax261.Infinite.Corollary.{a, b}\n" +
        "    (h₁ : _root_.Lax42.Primes.InfinitelyManyPrimes.{b})\n" +
        "    (h₂ : _root_.Lax42.Primes.ExistsPrimeDivisor)\n" +
        "    : _root_.Lax261.Infinite.Corollary.{a, b} := sorry\n",
    );
  });

  it("keeps a one-line body beside `:=`", () => {
    const composed = composeRelativeCertificate({
      target: { id: "Lax42.Primes.ExistsPrimeDivisor", levelParams: [] },
      given: [],
      proofs: PROOFS,
      witness: WITNESS,
    });
    expect(composed.body).toBe("@_root_.Lax7Proofs.existsPrimeDivisor");
    expect(
      relativeCertificateFiles({ theorem: composed.theorem, body: composed.body, conceptPackages: [], proofPackages: [] })["Solution.lean"],
    ).toContain("theorem Cert.Lax42.Primes.ExistsPrimeDivisor : _root_.Lax42.Primes.ExistsPrimeDivisor := @_root_.Lax7Proofs.existsPrimeDivisor\n");
  });

  it("refuses what the rules refuse, naming the rule", () => {
    const compose = (input: Partial<Parameters<typeof composeRelativeCertificate>[0]>) =>
      composeRelativeCertificate({
        target: { id: "Lax261.Infinite.Corollary", levelParams: ["a", "b"] },
        given: [],
        proofs: PROOFS,
        witness: WITNESS,
        ...input,
      });
    expect(() => compose({ given: [{ id: "Lax261.Infinite.Corollary", levelParams: ["a", "b"] }] })).toThrow(
      new CompositionError("Lax261.Infinite.Corollary is among the given statements; nothing is left to prove"),
    );
    expect(() => compose({ witness: new Map([...WITNESS].filter(([statement]) => statement !== "Lax42.Primes.ExistsPrimeDivisor")) })).toThrow(
      /Lax42\.Primes\.ExistsPrimeDivisor has no proof in the witness forest/u,
    );
    // a witness with a universe parameter its conclusion does not determine
    const loose = new Map(PROOFS);
    loose.set("Lax42Proofs.euclid", proof("Lax42Proofs.euclid", ["u", "extra"], [["Lax42.Primes.ExistsPrimeDivisor", []]], ["Lax42.Primes.InfinitelyManyPrimes", ["u"]]));
    expect(() => compose({ proofs: loose })).toThrow(/universe parameter extra, which its conclusion Lax42\.Primes\.InfinitelyManyPrimes does not determine/u);
    // a polymorphic given statement the composition never uses
    expect(() => compose({ given: [{ id: "Lax261.Infinite.Unused", levelParams: ["z"] }] })).toThrow(
      /does not use Lax261\.Infinite\.Unused, and Lax261\.Infinite\.Unused is universe-polymorphic/u,
    );
    // a given statement demanded at two instances
    const twice = new Map(PROOFS);
    twice.set(
      "Lax261Proofs.corollary",
      proof("Lax261Proofs.corollary", ["v", "w"], [["Lax42.Primes.InfinitelyManyPrimes", ["w"]], ["Lax42.Primes.InfinitelyManyPrimes", ["v"]]], ["Lax261.Infinite.Corollary", ["v", "w"]]),
    );
    expect(() => compose({ proofs: twice, given: [{ id: "Lax42.Primes.InfinitelyManyPrimes", levelParams: ["u"] }] })).toThrow(
      /needed at 2 universe instances \(Lax42\.Primes\.InfinitelyManyPrimes\.\{b\}, Lax42\.Primes\.InfinitelyManyPrimes\.\{a\}\); a hypothesis has one/u,
    );
    // a cyclic witness relation (selectProofTree never produces one)
    const cyclic = new Map(WITNESS);
    cyclic.set("Lax42.Primes.ExistsPrimeDivisor", "Lax261Proofs.corollary");
    expect(() => compose({ witness: cyclic })).toThrow(/is the witness of Lax42\.Primes\.ExistsPrimeDivisor but concludes Lax261\.Infinite\.Corollary/u);
  });
});
